package org.mifos.mobile

/**
 * Created by dilpreet on 26/6/17.
 */
object FakeJsonName {
    const val ACCOUNT_OPTION_TEMPLATE = "accountOptionTemplate.json"
    const val CLIENT_ACCOUNTS_JSON = "clientAccounts.json"
    const val CLIENT_SAVINGS_ACCOUNT_JSON = "clientSavingsAccounts.json"
    const val CLIENT_LOAN_ACCOUNT_JSON = "clientLoanAccounts.json"
    const val CLIENT_SHARE_ACCOUNT_JSON = "clientShareAccounts.json"
    const val BENEFICIARIES_JSON = "beneficiaries.json"
    const val BENEFICIARY_TEMPLATE_JSON = "beneficiaryTemplate.json"
    const val BENEFICIARY_PAYLOAD_JSON = "beneficiaryPayload.json"
    const val BENEFICIARY_UPDATE_PAYLOAD_JSON = "beneficiaryUpdatePayload.json"
    const val LOGIN = "login.json"
    const val LOAN_ACCOUNT_JSON = "loanAccount.json"
    const val LOAN_PAYLOAD_JSON = "loanPayload.json"
    const val LOAN_TEMPLATE_JSON = "loanTemplate.json"
    const val LOAN_TEMPLATE_BY_PRODUCT_JSON = "loanTemplateByProduct.json"
    const val LOAN_ACCOUNT_WITH_TRANSACTIONS_JSON = "loanAccountWithTransactions.json"
    const val LOAN_ACCOUNT_WITH_EMPTY_TRANSACTIONS_JSON = "loanAccountWithEmptyTransactions.json"
    const val LOAN_ACCOUNT_WITH_REPAYMENT_SCHEDULE_JSON = "loanAccountWithRepaymentSchedule.json"
    const val LOAN_ACCOUNT_WITH_EMPTY_REPAYMENT_SCHEDULE_JSON = "loanAccountWithEmptyRepaymentSchedule.json"
    const val CLIENTS_JSON = "clients.json"
    const val CLIENTS_NOT_FOUND_JSON = "clientsNotFound.json"
    const val USER_JSON = "user.json"
    const val TRANSACTIONS_JSON = "transactions.json"
    const val TRANFER_PAYLOAD_JSON = "transferPayload.json"
    const val SAVINGS_WITH_ASSOCIATIONS = "SavingsAccountWithAssociations.json"
    const val REGISTER = "register.json"
    const val CHARGE = "charge.json"
    const val SAVING_CHARGE = "savingCharge.json"
    const val LOAN_CHARGE = "loanCharge.json"
    const val USER_VERIFY_JSON = "userVerify.json"
    const val GUARANTOR_TEMPLATE = "guarantorTemplate.json"
    const val GUARANTOR_LIST = "guarantorList.json"
    const val SAVINGS_ACCOUNT_TEMPLATE = "savingsAccountTemplate.json"
    const val CLIENT_JSON = "client.json"
    const val UPDATE_PASSWORD_PAYLOAD_JSON = "updatePasswordPayload.json"
}