source 'https://cdn.cocoapods.org'
platform :ios, '16.0'
use_frameworks!

target 'iosApp' do
  project 'iosApp.xcodeproj'
  pod 'cmp_shared', :path => '../cmp-shared'

  # Native Firebase iOS Pods required by firebase-kotlin-sdk
  pod 'FirebaseCore'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable code signing for Pod targets
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''

      # Remove provisioning profile settings from Pod targets
      config.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
      config.build_settings.delete('PROVISIONING_PROFILE')
      config.build_settings.delete('DEVELOPMENT_TEAM')

      # Fix deployment target warnings
      deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if deployment_target && deployment_target.to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
