name: Workflow for master/development branches

on:
  pull_request:
  push:
    branches:
      - 'development'
      - 'master'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

        # Set up JDK
      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

        # Install NDK
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}

        # Update Gradle Permission
      - name: Change gradlew Permission
        run: chmod +x gradlew

        # Build App
      - name: Build with Gradle
        run: ./gradlew assemble

        # Upload Built APK
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: mifos-mobile
          path: app/build/outputs/apk/debug/

  lintCheck:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Static Analysis
        run: ./gradlew lint

      - name: Upload Static Analysis Report For Mifos-Mobile Module
        uses: actions/upload-artifact@v3.1.2
        if: failure()
        with:
          name: Static Analysis Report
          path: app/build/reports/

  pmd:
    name: PMD
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: PMD Check
        run: ./gradlew pmd

      - name: Upload PMD Report
        uses: actions/upload-artifact@v3.1.2
        if: failure()
        with:
          name: PMD Report
          path: app/build/reports/
